
language: swift

osx_image: xcode11.5
env:
  matrix:
    - TEST_SDK=iphonesimulator13.5 OS=13.5 NAME='iPhone 11'
    - TEST_SDK=iphonesimulator13.5 OS=13.5 NAME='iPhone 8'

install:
- gem install slather
script:
  - set -o pipefail && xcodebuild clean build test -enableCodeCoverage YES -project SwiftyLib.xcodeproj -scheme SwiftyLib -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES | xcpretty

after_success:
- slather
- bash <(curl -s https://codecov.io/bash) -f ./cobertura.xml -X coveragepy -X gcov -X xcode

